import json
import os
import unittest
import time
from pathlib import Path
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# Robust Pathing
SCRIPT_DIR = Path(__file__).parent.absolute()
PROJECT_ROOT = SCRIPT_DIR.parent
DATA_DIR = PROJECT_ROOT / "data"

class PokerIntegrationTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Configure Selenium
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        cls.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), 
            options=chrome_options
        )
        # Point to the REAL server started by server.py
        cls.url = "http://localhost:8000/index.html"

    @classmethod
    def tearDownClass(cls):
        if hasattr(cls, 'driver'):
            cls.driver.quit()

    def test_live_dashboard_results(self):
        """Verify the dashboard reflects the current winner.json data."""
        # 1. Load the actual data generated by the live run
        winner_file = DATA_DIR / "winner.json"
        self.assertTrue(winner_file.exists(), "winner.json was not generated!")
        
        with open(winner_file, 'r') as f:
            win_res = json.load(f)
        
        actual_winner_id = win_res["winner_id"] # e.g. "47928e71_0"
        winner_info = win_res["results"][actual_winner_id]

        # 2. Check the Browser
        self.driver.get(self.url)
        wait = WebDriverWait(self.driver, 10)
        
        # Verify the winner box exists and has the correct styling
        winner_box = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".player-box.winner")))
        
        # Extract ID prefix to match UI
        client_id_prefix = actual_winner_id.split('_')[0]
        self.assertIn(client_id_prefix, winner_box.text)
        
        # Verify hand type display matches the backend calculation
        hand_type_display = winner_box.find_element(By.CLASS_NAME, "hand-type").text
        self.assertEqual(hand_type_display, winner_info["hand_type"])

        # Verify status light is green
        status_light = self.driver.find_element(By.ID, "status-light")
        self.assertIn(status_light.value_of_css_property("background-color"), 
                     ["rgb(0, 255, 0)", "rgba(0, 255, 0, 1)"])

if __name__ == "__main__":
    unittest.main()